---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  # Go modules - separate block for each directory
  - package-ecosystem: "gomod"
    directory: "/cluster-agent"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/common"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/hardware-discovery-agent"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/node-agent"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/platform-telemetry-agent"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/platform-update-agent"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/device-discovery-agent"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/in-band-manageability"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"

  - package-ecosystem: "gomod"
    directory: "/reporting-agent"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gomod][reporting-agent] "
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"  # This searches in .github/workflows directory
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gha] "
    cooldown:
      default-days: 7
