# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

CI 🤖:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

root:
  - changed-files:
      - any-glob-to-any-file: "*"

cluster-agent:
  - changed-files:
    - any-glob-to-any-file: "cluster-agent/**"

common:
  - changed-files:
    - any-glob-to-any-file: "common/**"

hardware-discovery-agent:
  - changed-files:
    - any-glob-to-any-file: "hardware-discovery-agent/**"

node-agent:
  - changed-files:
    - any-glob-to-any-file: "node-agent/**"

platform-observability-agent:
  - changed-files:
    - any-glob-to-any-file: "platform-observability-agent/**"

platform-telemetry-agent:
  - changed-files:
      - any-glob-to-any-file: "platform-telemetry-agent/**"

platform-update-agent:
  - changed-files:
      - any-glob-to-any-file: "platform-update-agent/**"

reporting-agent:
  - changed-files:
      - any-glob-to-any-file: "reporting-agent/**"
