# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
version: v0.3.0
logLevel: info
onboarding:
  serviceURL: 'localhost:443'
metricsEndpoint: 'unix:///run/platform-observability-agent/platform-observability-agent.sock'
metricsInterval: 10s
interval: 30s
jwt:
  accessTokenPath: /etc/intel_edge_node/tokens/hd-agent/access_token
statusEndpoint: 'unix:///run/node-agent/node-agent.sock'
