#!/bin/bash

while true
do
	if [ -e /run/platform-observability-agent/agent-logs.sock ]; then
		echo "Starting Platform Observability Health Check Service"
		break
	else
		sleep 10
	fi
done

exec "$@"
