#!/bin/bash

while true
do
	if [ -f /etc/intel_edge_node/tokens/platform-observability-agent/access_token ]; then
	        echo "Starting Platform Observability Collector Service"
		break
	else
        	sleep 10
	fi
done

exec "$@"
