#!/bin/bash
set -e

# Create the directories and set permissions
mkdir -p /var/intel-manageability
chown root:root /var/intel-manageability
chmod 640 /var/intel-manageability

mkdir -p /var/cache/manageability/repository-tool/sota
chmod 640 /var/cache/manageability/repository-tool/sota
mkdir -p /var/cache/manageability/repository-tool/sota/metadata

exit 0
