# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 'v0.5.0'

# Globally unique identifier read from motherboard. Might be obtained with:
# sudo cat /sys/class/dmi/id/product_uuid
GUID: '00000000-0000-0000-0000-000000000000'

logLevel: 'debug'

metricsEndpoint: 'unix:///run/platform-observability-agent/platform-observability-agent.sock'
metricsInterval: 10s
statusEndpoint: 'unix:///run/node-agent/node-agent.sock'
# Connection parameters
clusterOrchestratorURL: 'localhost:443'
heartbeat: '10s'
jwt:
  accessTokenPath: '/etc/intel_edge_node/tokens/cluster-agent/access_token'
