# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 'v0.1.0'
logLevel: info
GUID: '00000000-0000-0000-0000-000000000000'
updateServiceURL: 'localhost:8089'
metadataPath: '/var/edge-node/pua/metadata.json'
INBCLogsPath: '/var/log/inbm-update-status.log'
INBCGranularLogsPath: '/var/log/inbm-update-log.log'
metricsEndpoint: 'unix:///run/platform-observability-agent/platform-observability-agent.sock'
metricsInterval: 10s
statusEndpoint: 'unix:///run/node-agent/node-agent.sock'
tickerInterval: 10s
jwt:
  accessTokenPath: '/etc/intel_edge_node/tokens/platform-update-agent/access_token'
immediateDownloadWindow: 10m
downloadWindow: 6h
releaseServiceFQDN: 'https://files-rs.internal.example.intel.com'
