#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_get platform-manageability-agent/manageability.serviceURL
if [ ! -z "$RET" ]; then
    sed -i "s/^  serviceURL: '.*'/  serviceURL: '$RET'/" /etc/edge-node/node/confs/platform-manageability-agent.yaml
fi

db_get platform-manageability-agent/rpsAddress
if [ ! -z "$RET" ]; then
    sed -i "s/^rpsAddress: '.*'/rpsAddress: '$RET'/" /etc/edge-node/node/confs/platform-manageability-agent.yaml
fi

db_get platform-manageability-agent/metrics.enabled
if [ ! -z "$RET" ]; then
    sed -i -e '/^metrics:$/{n' -e 's/enabled:.*/enabled: '"$RET"'/' -e '}' /etc/edge-node/node/confs/platform-manageability-agent.yaml
fi

# Create system group if it doesn't exist
groupadd -f bm-agents --system

# Create system user if it doesn't exist
id -u pm-agent >/dev/null 2>&1 || useradd pm-agent --system -g bm-agents -s /sbin/nologin

GUID="$(cat /sys/class/dmi/id/product_uuid)"
sed -i "s/^GUID: '.*'/GUID: '$GUID'/" /etc/edge-node/node/confs/platform-manageability-agent.yaml

#DEBHELPER#
