#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_input high node-agent/onboarding.serviceURL || true
db_input low node-agent/onboarding.enabled || true
db_input low node-agent/onboarding.heartbeatInterval || true
db_input low node-agent/status.serviceClients || true
db_input low node-agent/status.outboundClients || true
db_input low node-agent/metrics.enabled || true
db_input low node-agent/auth.accessTokenURL || true
db_input low node-agent/auth.rsTokenURL || true
db_input low node-agent/auth.tokenClients || true
db_input low node-agent/proxy.aptSourceURL || true
db_input low node-agent/proxy.aptSourceProxyPort || true
db_input low node-agent/proxy.aptSourceFilesRSRoot || true
db_input low node-agent/auth.RSType || true
db_go || true
